# Generated by Django 3.2.7 on 2021-09-09 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
